layout_spectrum: 0.4058591985351194
typography_spectrum: 0.6563454652352646
color:
  brandStrength: 0.3211589240379595
  lightness: 0.5058739910865812
  saturation: 0.6418347588040414
  rhythmicContrast: 0.18240812453413657
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: kbFood
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/db8bc669-d6f5-4c35-99e3-bd971696f61e.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/db8bc669-d6f5-4c35-99e3-bd971696f61e.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b1e1b95b-ef86-468d-978a-77d9d4a0032e.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b1e1b95b-ef86-468d-978a-77d9d4a0032e.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/865e9772-f201-4d0a-a902-c18fe5cdbe74.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/865e9772-f201-4d0a-a902-c18fe5cdbe74.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5771ab52-49a2-4ca9-8caa-72dcc7ac8d0f.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5771ab52-49a2-4ca9-8caa-72dcc7ac8d0f.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://food.kosnerburstein.com'
analytics:
  google: UA-104323546-3
title: Food By KB
description: Ultimate Food!!
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0149a692-7ae8-4d49-9830-bba19975b6c5.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/268a2d0d-612f-4589-af55-4bb2f1f5c785.png
github: true
